class EnvParser:
    """convert environment status/action to vectors"""

    ...
    """
    def get_legal_mask(game_status, player_id) -> list[bool]:
        ...
    def encode_observation(game_status, player_id) -> Vector:
        ...
    def decode_action(action_id)->SpecificGameActionObject:
        ...
    """
